#!/usr/bin/env python3
"""Regenerate the website's page previews after replacing cv.pdf.

Requires Poppler's pdftoppm command (macOS: brew install poppler).
The original PDF is never modified.
"""

import hashlib
from pathlib import Path
import shutil
import struct
import subprocess
import tempfile


def main():
    root = Path(__file__).resolve().parents[1]
    source = root / "cv.pdf"
    renderer = shutil.which("pdftoppm")
    if not renderer:
        raise SystemExit("Install Poppler to provide pdftoppm, then run this script again.")

    with tempfile.TemporaryDirectory(prefix="cv-preview-") as temporary:
        prefix = Path(temporary) / "page"
        subprocess.run([renderer, "-r", "180", "-png", str(source), str(prefix)], check=True)
        previews = sorted(
            Path(temporary).glob("page-*.png"),
            key=lambda page: int(page.stem.rsplit("-", 1)[1]),
        )
        if not previews:
            raise SystemExit("The PDF renderer did not produce any pages.")

        destination = root / "assets" / "cv"
        destination.mkdir(parents=True, exist_ok=True)
        data = [
            "# Generated by scripts/update_cv_preview.py; do not edit by hand.",
            "pdf_sha256: " + hashlib.sha256(source.read_bytes()).hexdigest(),
            "pages:",
        ]
        for index, preview in enumerate(previews, start=1):
            width, height = struct.unpack(">II", preview.read_bytes()[16:24])
            filename = "page-{}.png".format(index)
            shutil.copyfile(preview, destination / filename)
            data.extend([
                "  - image: /assets/cv/" + filename,
                "    width: " + str(width),
                "    height: " + str(height),
            ])

        expected = {"page-{}.png".format(i) for i in range(1, len(previews) + 1)}
        for old_preview in destination.glob("page-*.png"):
            if old_preview.name not in expected:
                old_preview.unlink()
        (root / "_data" / "cv_preview.yml").write_text("\n".join(data) + "\n")
        print("Updated {} CV page previews.".format(len(previews)))


if __name__ == "__main__":
    main()
